<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-worker_orders-e91fe8e2-d132-4ba1-a253-0f399e23bf0f</UserSecretsId>
    <RootNamespace>worker_orders</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api-poc-tmb\api-poc-tmb.csproj">
      <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
