services:
  api-poc-tmb:
    image: ${DOCKER_REGISTRY-}apipoctmb
    build:
      context: .
      dockerfile: api-poc-tmb/Dockerfile
    depends_on:
      - postgresql-poc-tmb

  postgresql-poc-tmb:
    image: postgres:15
    container_name: postgresql-poc-tmb
    environment:
      - POSTGRES_USER=backend-user
      - POSTGRES_PASSWORD=Tw2cDZOca41W
      - POSTGRES_DB=ordersdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend-user"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker-poc-tmb:
    image: ${DOCKER_REGISTRY-}apipoctmb
    build:
      context: .
      dockerfile: worker-orders/Dockerfile

volumes:
  pgdata:
